### ISSUE TITLE
Broken again

### ISSUE THREAD

**Issue by GenifeUA** [ading2210/poe-api#114]
Invalid or missing token. 

Poe added new cookie - g_state.

**Comment by Anandkrishna34** [comment]
Just use pip install --upgrade poe-api

**Comment by ading2210** [comment]
g_state just seems to be a unix timestamp containing when the client logged in.

**Comment by Zapzatron** [comment]
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\Zapzatron_Bot_Async.py", line 1160, in gpt4_32
    response_text, gpt4_32_context, temp_message = await gpt_all(message, command_name, prompt, model, keys,
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\Zapzatron_Bot_Async.py", line 901, in gpt_all
    raise e
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\Zapzatron_Bot_Async.py", line 872, in gpt_all
    response_text, chat_context, number_remain_messages = await gpt_poe(prompt, model, keys[0],
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\Zapzatron_Bot_Async.py", line 731, in gpt_poe
    client = poe.Client(key)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\poe.py", line 150, in __init__
    self.connect_ws()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\poe.py", line 411, in connect_ws
    self.setup_connection()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\poe.py", line 176, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\poe.py", line 218, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\poe.py", line 76, in request_with_retries
    raise RuntimeError("Invalid or missing token.")
RuntimeError: Invalid or missing token.
