### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by manm15** [ading2210/poe-api#119]
Got an error, I don't know why. I have already checked multiple issues on this github but why won't it work?

`Traceback (most recent call last):
  File "C:/Users/ManM15/OneDrive - Berkhamsted Schools Group/Documents/Code/Poe.py", line 3, in <module>
    client = poe.Client("FQvugE1iK7jI0BKGrReYBQ%3D%3D")
  File "C:\Users\ManM15\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\poe.py", line 123, in __init__
    self.connect_ws()
  File "C:\Users\ManM15\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\poe.py", line 365, in connect_ws
    self.setup_connection()
  File "C:\Users\ManM15\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\poe.py", line 149, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "C:\Users\ManM15\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\poe.py", line 193, in get_next_data
    json_text = re.search(json_regex, r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by riusksk** [comment]
hit the same error

**Comment by asce0** [comment]
get the same error, is there any help?

**Comment by monshizadeh** [comment]
same here from yday. even tried different account and token. still same error!
