### ISSUE TITLE
Connection timeout when using socks5 proxy

### ISSUE THREAD

**Issue by WeeAris** [ading2210/poe-api#126]
I use socks5 proxy with [nekoray](https://github.com/MatsuriDayo/nekoray/releases), but it seems doesn't work.

**Comment by ading2210** [comment]
Try using `socks5h://` instead of `socks5://`.

**Comment by WeeAris** [comment]
> Try using `socks5h://` instead of `socks5://`.

```
Traceback (most recent call last):
  File "/home/wee/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/.local/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/home/wee/.local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/wee/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/wee/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/wee/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/wee/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/wee/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/wee/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/wee/.local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/wee/.local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/wee/.local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/wee/.local/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/.local/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/MyApps/run/AITranslatorProxy/main.py", line 175, in trans
    translation_result = pbt.translate(origin_text_dict=source_dict,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/MyApps/run/AITranslatorProxy/tools/poebot.py", line 22, in translate
    client = poe.Client(cookie, proxy=self.proxy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/.local/lib/python3.11/site-packages/poe.py", line 123, in __init__
    self.connect_ws()
  File "/home/wee/.local/lib/python3.11/site-packages/poe.py", line 366, in connect_ws
    self.setup_connection()
  File "/home/wee/.local/lib/python3.11/site-packages/poe.py", line 149, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/.local/lib/python3.11/site-packages/poe.py", line 191, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/.local/lib/python3.11/site-packages/poe.py", line 45, in request_with_retries
    r = method(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/.local/lib/python3.11/site-packages/tls_client/sessions.py", line 422, in get
    return self.execute_request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wee/.local/lib/python3.11/site-packages/tls_client/sessions.py", line 405, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to build client out of request input: scheme socks5h is not supported

```

**Comment by ichuixue** [comment]
Change  `def connect_ws(self, timeout=5)` in poe.py to `def connect_ws(self, timeout=10)`. You can use `http://` for proxy.
