### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by x169x** [ading2210/poe-api#148]
###   **I started to get this error starting from version 0.4.8 when I run my code:**
 
```
            for chunk in poe_client.send_message(poe_model, sentence_messages, with_chat_break=True):
                pass

            print(f'{"":=^160}')
            print(f'Response for {message.author.name}: {chunk["text"]}')
            reply = chunk["text"]
```

### **Error code:**
```
Exception in thread
Thread-32 (recv_post_thread)Response for x169x: Hi, x169x!:


Traceback (most recent call last):
  File "C:\Users\shely\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
  self.run()
  File "C:\Users\shely\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
  self._target(*self._args, **self._kwargs)
  None  File "C:\Users\shely\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 564, in recv_post_thread
  
  bot_message_id = self.active_messages[human_message_id]
  KeyError: 1636771016
```

**Comment by zhouhh2017** [comment]
Same problem
