### ISSUE TITLE
Seems like the API not working

### ISSUE THREAD

**Issue by valokobito** [ading2210/poe-api#161]
1. I've cloned the repo.
2. Ran `pip3 install poe-api`.
3.  Ran `python3 examples/temporary_message.py`.

Then i've got:
```
bash-3.2$ python3 examples/temporary_message.py 
ERROR:websocket:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992) - goodbye
WARNING:root:Websocket closed with status None: None
ERROR:websocket:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992) - goodbye

// same logs a few more times

WARNING:root:Websocket closed with status None: None
Traceback (most recent call last):
  File "<PATH_TO_THE_PROJECT>/examples/temporary_message.py", line 4, in <module>
    client = poe.Client("<TOKEN>") 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/poe.py", line 150, in __init__
    self.connect_ws()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/poe.py", line 438, in connect_ws
    raise RuntimeError("Timed out waiting for websocket to connect.")
RuntimeError: Timed out waitin
```

My `examples/temporary_message.py` file:
```py
import poe
import logging

client = poe.Client("<TOKEN>") # Here I provide my real token

print(client.bot_names)
```

Details:
* `websocket-client`: version 1.6.1
* python3: version3.11.1

What do I wrong?

**Comment by valokobito** [comment]
Fixed it!

According to the following answer:
[https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error#comment93046025_45018725](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error#comment93046025_45018725)
