### ISSUE TITLE
1、json issue  2、 request Issues

### ISSUE THREAD

**Issue by isJN** [ading2210/poe-api#178]
ps:Please forgive my poor English

1、one of the codes is about the generation of device_id, but there are some problems. After each generation, it will be written into a json file. If it is multi-threaded or in other cases, the json file will report an error and the format will be wrong. You can improve it by modifying the code in poe.py
2、The problem of websocket request can be improved by modifying the request header before, but it is no longer possible. The error about this is as follows
“”“
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...
ERROR:websocket:error from callback <bound method Client.on_ws_cl.......
”“”
sometimes the request fails, sometimes the pull fails
The above is my personal understanding

**Comment by isJN** [comment]
full error
“”“
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...
Traceback (most recent call last):
  File "x\xxx\test.py", line 50, in <module>
    get_answer(token='LcB2MHpOcQJaHDZfh2HdCw%3D%3D',query=quer)
  File "x\xxx\test.py", line 21, in get_answer
    client = poe.Client(token=token,proxy='http://127.0.0.1:7890')
  File "D:\anaconda\lib\site-packages\poe.py", line 157, in __init__
    self.connect_ws()
  File "D:\anaconda\lib\site-packages\poe.py", line 418, in connect_ws
    self.setup_connection()
  File "D:\anaconda\lib\site-packages\poe.py", line 183, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "D:\anaconda\lib\site-packages\poe.py", line 225, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
  File "D:\anaconda\lib\site-packages\poe.py", line 82, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com too many times.

Process finished with exit code 1

”“”

**Comment by isJN** [comment]
> #158 的副本。

Thank you for your reply. After my test, it is the problem of ip

**Comment by Qewertyy** [comment]
> > #158 的副本。
> 
> Thank you for your reply. After my test, it is the problem of ip

how did you fixed it?

**Comment by isJN** [comment]
Yes, it did work after I changed the proxy address, which means my ip was detected or disabled for a short time

发件人: Qewertyy ***@***.***>
发送时间: 2023年7月21日 23:21
收件人: ading2210/poe-api ***@***.***>
抄送: JN ***@***.***>; Author ***@***.***>
主题: Re: [ading2210/poe-api] 1、json issue 2、 request Issues (Issue #178)


#158<https://github.com/ading2210/poe-api/issues/158> 的副本。

Thank you for your reply. After my test, it is the problem of ip

how did you fixed it?
