### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by DarkLorianPrime** [ading2210/poe-api#185]
Hello! I've upgraded to 0.4.12, but I still have this exception.
Full exception:
```python
Traceback (most recent call last):
  File "/Users/darklorian/PycharmProjects/keihelper/test.py", line 8, in <module>
    client = poe.Client(os.getenv("token"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darklorian/PycharmProjects/keihelper/venv/lib/python3.11/site-packages/poe.py", line 152, in __init__
    self.connect_ws()
  File "/Users/darklorian/PycharmProjects/keihelper/venv/lib/python3.11/site-packages/poe.py", line 406, in connect_ws
    self.setup_connection()
  File "/Users/darklorian/PycharmProjects/keihelper/venv/lib/python3.11/site-packages/poe.py", line 178, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darklorian/PycharmProjects/keihelper/venv/lib/python3.11/site-packages/poe.py", line 227, in get_next_data
    self.formkey = self.extract_formkey(r.text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darklorian/PycharmProjects/keihelper/venv/lib/python3.11/site-packages/poe.py", line 204, in extract_formkey
    script_text = re.search(script_regex, html).group(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```
I apologize for the duplicate, but in that issue it seemed to me that the issue was resolved...

**Comment by RamyGomaa** [comment]
me too, I also upgraded it to the latest version..

**Comment by claell** [comment]
Also see #184

**Comment by DarkLorianPrime** [comment]
> Also see #184

We posted at about the same time, so I didn't see his issue

**Comment by ading2210** [comment]
This is the same underlying issue as #184.

**Comment by canxin121** [comment]
> This is the same underlying issue as #184.

I recommend you not to use js to solve the problem. I will give you a new pr now.
