### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by Hammour-steak** [ading2210/poe-api#19]
I would like to ask that I have obtained the token now, but an error occurred while running the example:
**running code:**
```
import poe
import logging
import sys

#send a message and immediately delete it

client = poe.Client("TaUcK33UPMDeOqTB8MigqA%3D%3D")

message = "Who are you?"
for chunk in client.send_message("capybara", message, with_chat_break=True):
  print(chunk["text_new"], end="", flush=True)

#delete the 3 latest messages, including the chat break
client.purge_conversation("capybara", count=3)
```

**exception:**
Traceback (most recent call last):
  File "C:/Users/hammour/Desktop/poe-api-main/examples/temporary_message.py", line 7, in <module>
    client = poe.Client("TaUcK33UPMDeOqTB8MigqA%3D%3D", proxy="socks5://127.0.0.1:7890")
  File "C:\Users\hammour\Desktop\poe-api-main\poe-api\src\poe.py", line 73, in __init__
    self.next_data = self.get_next_data()
  File "C:\Users\hammour\Desktop\poe-api-main\poe-api\src\poe.py", line 89, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
  File "C:\Users\hammour\Desktop\poe-api-main\poe-api\src\poe.py", line 32, in request_with_retries
    r = method(*args, **kwargs)
  File "D:\Anaconda\envs\cvstudy\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "D:\Anaconda\envs\cvstudy\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\cvstudy\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\cvstudy\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='poe.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

It seems like this code is wrong:
`client = poe.Client("TaUcK33UPMDeOqTB8MigqA%3D%3D")`

**Comment by ading2210** [comment]
>  `requests.exceptions.ProxyError: HTTPSConnectionPool(host='poe.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))`

It seems that you're trying to connect with a proxy. Can you verify that your proxy works on poe.com and other sites?

**Comment by Hammour-steak** [comment]
Yes, it works well on poe, google or youtube

**Comment by Hammour-steak** [comment]
and i try to add an argument in poe.Client:
`proxy="socks5://127.0.0.1:7890"`
it still broken.

**Comment by ading2210** [comment]
Maybe try the `socks5h` protocol, which also proxies the DNS queries? Also, are you able to use the same proxy with the python requests module in a different script?

**Comment by Mr-Cong** [comment]
I meet the same problem.I tried pip install urllib3==1.25.11 and the problem is resovled.

**Comment by def-saizi-baka** [comment]
> I would like to ask that I have obtained the token now, but an error occurred while running the example: **running code:**
> 
> ```
> import poe
> import logging
> import sys
> 
> #send a message and immediately delete it
> 
> client = poe.Client("my token")
> 
> message = "Who are you?"
> for chunk in client.send_message("capybara", message, with_chat_break=True):
>   print(chunk["text_new"], end="", flush=True)
> 
> #delete the 3 latest messages, including the chat break
> client.purge_conversation("capybara", count=3)
> ```
> 
> **exception:** Traceback (most recent call last): File "C:/Users/hammour/Desktop/poe-api-main/examples/temporary_message.py", line 7, in client = poe.Client("my token", proxy="socks5://127.0.0.1:7890") File "C:\Users\hammour\Desktop\poe-api-main\poe-api\src\poe.py", line 73, in **init** self.next_data = self.get_next_data() File "C:\Users\hammour\Desktop\poe-api-main\poe-api\src\poe.py", line 89, in get_next_data r = request_with_retries(self.session.get, self.home_url) File "C:\Users\hammour\Desktop\poe-api-main\poe-api\src\poe.py", line 32, in request_with_retries r = method(*args, **kwargs) File "D:\Anaconda\envs\cvstudy\lib\site-packages\requests\sessions.py", line 555, in get return self.request('GET', url, **kwargs) File "D:\Anaconda\envs\cvstudy\lib\site-packages\requests\sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "D:\Anaconda\envs\cvstudy\lib\site-packages\requests\sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "D:\Anaconda\envs\cvstudy\lib\site-packages\requests\adapters.py", line 510, in send raise ProxyError(e, request=request) requests.exceptions.ProxyError: HTTPSConnectionPool(host='poe.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
> 
> It seems like this code is wrong: `client = poe.Client("my token")`

Try http://127.0.0.1:7890 ?
