### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ahmadperformve** [ading2210/poe-api#202]
I am using Windows 11 and have updated the poe-api module to Version: 0.4.17 but I am getting this error. 

Traceback (most recent call last):
  File "c:\Users\ThinkPad\Desktop\PerformVE\sentiment_analysis_api\Sentiment_Analysis_3\main.py", line 144, in <module>
    client = poe.Client(token)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 152, in __init__
    self.connect_ws()
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 405, in connect_ws
    self.setup_connection()
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 178, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 226, in get_next_data
    self.formkey = self.extract_formkey(r.text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ThinkPad\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 203, in extract_formkey
    script_text = re.search(script_regex, html).group(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ak7660** [comment]
Same issue, is there a way to solve it?

**Comment by greengeckowizard** [comment]
same issue here

**Comment by pzq7025** [comment]
you can update the package to solve the problem：
```shell
pip install -U poe-api
```
but you will meet a new issues:
```text
RuntimeError: Failed to download https://poe.com too many times.
```

**Comment by pzq7025** [comment]
A very strange phenomenon is that although I encountered this bug after the update, it disappeared after running the program multiple times. 
I suspect it is related to this issue [#issues193](https://github.com/ading2210/poe-api/issues/193).

**Comment by ahmadperformve** [comment]
Yes now I am getting:
RuntimeError: Failed to download https://poe.com too many times.

**Comment by ahmadperformve** [comment]
> you can update the package to solve the problem：
> 
> ```shell
> pip install -U poe-api
> ```
> 
> but you will meet a new issues:
> 
> ```
> RuntimeError: Failed to download https://poe.com too many times.
> ```

I have already updated to the latest version but still face the issue!

**Comment by ading2210** [comment]
For now, try specifying the formkey manually.
