### ISSUE TITLE
ReferenceError: 'document' is not defined

### ISSUE THREAD

**Issue by ydengf** [ading2210/poe-api#219]
Error in site-packages/poe/__init__.py

```
206   def extract_formkey(self, html, app_script):
         ... .... 
227     context = quickjs.Context()
228     formkey = context.eval(script_text)
         ... .... 
239     return formkey, salt
```

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/EdgeGPT/main.py", line 205, in asKPoe
    client = poe.Client("C18zAniejliR6466nvbz1w%3D%3D")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/poe/__init__.py", line 156, in __init__
    self.connect_ws()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/poe/__init__.py", line 446, in connect_ws
    self.setup_connection()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/poe/__init__.py", line 182, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/poe/__init__.py", line 254, in get_next_data
    self.formkey, self.formkey_salt = self.extract_formkey(r.text, r2.text)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/poe/__init__.py", line 228, in extract_formkey
    formkey = context.eval(script_text)
_quickjs.JSException: ReferenceError: 'document' is not defined
    at <anonymous> (<input>)
    at <eval> (<input>:9)
```

**Comment by ading2210** [comment]
This is fixed in the latest commit.
