### ISSUE TITLE
Connection to websocket timed out, please fix

### ISSUE THREAD

**Issue by 239144498** [ading2210/poe-api#6]
The error is as follows, the code was fine the last time it was run
```
Traceback (most recent call last):
  File "other\aa.py", line 253, in <module>
    main()
  File "other\aa.py", line 248, in main
    for chunk in client.send_message("capybara", message, with_chat_break=True):
  File "other\aa.py", line 159, in send_message
    ws.connect(url, header={"User-Agent": user_agent})
  File "Python\Python310\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "Python310\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "Python310\site-packages\websocket\_http.py", line 197, in _open_socket
    raise error
  File "Python310\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
TimeoutError: [WinError 10060] The connection attempt failed because the connecting party did not reply correctly after a certain period of time or the connected host did not respond.
```

**Comment by ading2210** [comment]
Is quora.com blocked in your region? In the US at least, everything seems to work fine.

**Comment by 239144498** [comment]
> quora.com 在您所在的地区被屏蔽了吗？ 至少在美国，一切似乎都很好。

感谢，

> Is quora.com blocked in your region? In the US at least, everything seems to work fine.

Thanks, found out it was not proxied to that ip

**Comment by ading2210** [comment]
I'm gonna reopen this issue until I implement a way to proxy the websocket connection.

**Comment by ading2210** [comment]
Proxy support has been added in 0.2.2.

**Comment by BenjiKCF** [comment]
Hi, may I know what should be the proxy address?

**Comment by ading2210** [comment]
@BenjiKCF Any socks5/socks4/http/https proxy should work fine.
