### ISSUE TITLE
Cannot send message? Object of type Message is not JSON serializable

### ISSUE THREAD

**Issue by BingusCoOfficial** [ading2210/poe-api#70]
Whenever i try to send a message using this function: 
```py
async def generate_response(message):
    with open("message.txt", "w") as f:
        for chunk in client.send_message("capybara", message):
            f.write(chunk["text_new"], end="", flush=True)
    with open("message.txt", "r+") as f:
        return f.read()
```
I just get this error:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/Bowkii/venv/lib/python3.9/site-packages/nextcord/client.py", line 512, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 370, in on_message
    response = await generate_response(message)
  File "main.py", line 14, in generate_response
    for chunk in client.send_message("capybara", message):
  File "/home/runner/Bowkii/venv/lib/python3.9/site-packages/poe.py", line 329, in send_message
    message_data = self.send_query("SendMessageMutation", {
  File "/home/runner/Bowkii/venv/lib/python3.9/site-packages/poe.py", line 202, in send_query
    payload = json.dumps(json_data, separators=(",", ":"))
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Message is not JSON serializable
```
I'm pretty sure I did everything correctly and I have not seen anybody else with this error

**Comment by ading2210** [comment]
`client.send_message` will only accept strings for the message input. You're trying to pass a `Message` object into the function, which can't be JSON serialized by the library.

**Comment by BingusCoOfficial** [comment]
message is a string though
