### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by 40740** [ading2210/poe-api#89]
INFO:root:Downloading next_data...
Traceback (most recent call last):
  File "G:\AI\poe\poe\poe-api-main\poe-api-main\examples\send_message.py", line 10, in <module>
    client = poe.Client(token)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 129, in __init__
    self.setup_connection()
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 134, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 173, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 45, in request_with_retries
    r = method(*args, **kwargs)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\tls_client\sessions.py", line 422, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\tls_client\sessions.py", line 405, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://poe.com": dial tcp: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by 40740** [comment]
client = poe.Client(token,client_identifier=None)
print(json.dumps(client.bot_names, indent=2))
///
PS G:\AI\poe\poe>  python 1.py
INFO:root:Downloading next_data...
INFO:root:Downloading channel data...
INFO:root:Downloading all bots...
INFO:root:Subscribing to mutations

**Comment by 40740** [comment]
My browser can access poe.com. don't know what's the problem

**Comment by 40740** [comment]
client = poe.client("xxxxx", client_identifier=None)

INFO:root:Downloading next_data...
INFO:root:Downloading channel data...
INFO:root:Downloading all bots...
INFO:root:Subscribing to mutations

It's stuck here the whole time

**Comment by alqasemy2020** [comment]
> client = poe.client("xxxxx", client_identifier=None)
> 
> INFO:root:Downloading next_data... INFO:root:Downloading channel data... INFO:root:Downloading all bots... INFO:root:Subscribing to mutations
> 
> It's stuck here the whole time

Remove the `client_identifier=None` part and it should work just fine (it will be set to `"firefox_102"` by default). 
> See the [Python-TLS-Client documentation](https://github.com/FlorianREGAZ/Python-Tls-Client#examples) for some sample values.

**Comment by IGamesI** [comment]
Did you manage to get this fixed?
