### ISSUE TITLE
payload none

### ISSUE THREAD

**Issue by jhkmichael** [ading2210/poe-api#90]
INFO:root:Proxy enabled: http://127.0.0.1:10809
INFO:root:Downloading next_data...
Traceback (most recent call last):
  File "C:\Users\ake\Desktop\fuyuan_spider\fuyuan.py", line 1194, in <module>
    test_quora()
  File "C:\Users\ake\Desktop\fuyuan_spider\fuyuan.py", line 527, in test_quora
    client = poe.Client("5itGguf7PP-LEV1PFfCp0w==", proxy="http://127.0.0.1:10809")
  File "C:\Users\ake\Desktop\fuyuan_spider\venv\lib\site-packages\poe.py", line 129, in __init__
    self.setup_connection()
  File "C:\Users\ake\Desktop\fuyuan_spider\venv\lib\site-packages\poe.py", line 134, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "C:\Users\ake\Desktop\fuyuan_spider\venv\lib\site-packages\poe.py", line 182, in get_next_data
    self.viewer = next_data["props"]["pageProps"]["payload"]["viewer"]
TypeError: 'NoneType' object is not subscriptable

then i print the nextdata：
{'props': {'bid': 'i delete this by myshelf', 'userAgent': 'Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0', 'middlewareStart': '1685637063707', 'path': '/', 'theme': 'auto', 'pageProps': {'payload': None, 'queryVariables': {}, 'additionalProps': {}, 'i18nInstanceState': {'ns': ['translation'], 'lng': 'en'}}, '__N_SSP': True}, 'page': '/', 'query': {}, 'buildId': '-lpSZI2JLoXKjVELA9OPH', 'assetPrefix': 'https://psc2.cf2.poecdn.net/9hi8jX6RrhgsWqa0dT1CxJS8', 'isFallback': False, 'gssp': True, 'appGip': True, 'scriptLoader': []}

Im pretty sure my m_b is correct, because the code had already load the formkey.
Please help! tks a lot

**Comment by ading2210** [comment]
This is a duplicate of #88.
